# Generated by Django 5.0.6 on 2024-06-08 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo', models.IntegerField()),
                ('apresentacao', models.CharField(max_length=500)),
                ('objetivos', models.CharField(max_length=500)),
                ('competencias', models.CharField(max_length=500)),
                ('ects', models.IntegerField()),
                ('duracao_semestres', models.IntegerField()),
                ('departamento', models.CharField(max_length=255)),
                ('contacto_direcao', models.CharField(max_length=255)),
                ('email_direcao', models.EmailField(max_length=254)),
                ('contacto_secretaria', models.CharField(max_length=255)),
                ('email_secretaria', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ano', models.IntegerField()),
                ('semestre', models.CharField(max_length=20)),
                ('ects', models.FloatField()),
                ('codigo_leitura', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('disciplinas', models.ManyToManyField(to='curso.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500)),
                ('conceitos_aplicados', models.CharField(max_length=500)),
                ('tecnologias_usadas', models.CharField(max_length=500)),
                ('imagem', models.ImageField(upload_to='')),
                ('video_link', models.URLField()),
                ('github_link', models.URLField()),
                ('disciplina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='curso.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='LinguagemProgramacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('projetos', models.ManyToManyField(to='curso.projeto')),
            ],
        ),
    ]
