# Generated by Django 5.0.6 on 2024-07-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_curso_disciplinas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='disciplinas',
            field=models.ManyToManyField(related_name='docentes', to='curso.disciplina'),
        ),
    ]
