# Generated by Django 5.0.6 on 2024-06-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='banda_ativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='banda',
            name='lancamento_primeiro_album',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='banda',
            name='descricao',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='banda',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
