# Generated by Django 5.0.6 on 2024-07-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0002_utilizador_remove_rating_autor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='rating_final',
        ),
        migrations.AddField(
            model_name='artigo',
            name='media_ratings',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='valor',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
