# Generated by Django 5.0.6 on 2024-07-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0003_remove_artigo_rating_final_artigo_media_ratings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='email',
            field=models.EmailField(default='123@gmail.com', max_length=254),
        ),
    ]
