# Generated by Django 5.0.6 on 2024-07-22 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0005_remove_utilizador_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('artigo', 'utilizador')},
        ),
    ]
